<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Subcategory;
use App\Models\Product;
use App\Models\User;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $sellerIds = User::where('is_seller', true)
            ->pluck('id')
            ->toArray();

        if (empty($sellerIds)) {
            return; // Если нет продавцов, выходим
        }

        $products = [
            // Категория: Электроника (существующие товары)
            [
                'name' => 'Смартфон Galaxy S23',
                'category' => 'electronics',
                'subcategory' => 'Смартфоны',
                'description' => 'Современный смартфон с мощным процессором и камерой 108 МП.',
                'price' => 799.99,
                'stock' => 30,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Ноутбук ASUS ROG',
                'category' => 'electronics',
                'subcategory' => 'Ноутбуки',
                'description' => 'Игровой ноутбук с процессором i9 и видеокартой RTX 4080.',
                'price' => 1999.99,
                'stock' => 15,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Умные часы Xiaomi',
                'category' => 'electronics',
                'subcategory' => 'Умные часы',
                'description' => 'Смарт-часы с функцией отслеживания активности.',
                'price' => 99.99,
                'stock' => 50,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Новые товары для электроники
            [
                'name' => 'Планшет iPad Air',
                'category' => 'electronics',
                'subcategory' => 'Планшеты',
                'description' => 'Планшет с экраном Retina и чипом M1.',
                'price' => 599.99,
                'stock' => 20,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Наушники Sony WH-1000XM5',
                'category' => 'electronics',
                'subcategory' => 'Аудиотехника',
                'description' => 'Беспроводные наушники с шумоподавлением.',
                'price' => 349.99,
                'stock' => 25,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Камера Canon EOS R6',
                'category' => 'electronics',
                'subcategory' => 'Камеры и фотоаппараты',
                'description' => 'Беззеркальная камера с высоким разрешением.',
                'price' => 2499.99,
                'stock' => 10,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Консоль PlayStation 5',
                'category' => 'electronics',
                'subcategory' => 'Игровые консоли',
                'description' => 'Игровая консоль нового поколения.',
                'price' => 499.99,
                'stock' => 15,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Зарядное устройство Anker',
                'category' => 'electronics',
                'subcategory' => 'Аксессуары для электроники',
                'description' => 'Быстрое зарядное устройство USB-C.',
                'price' => 29.99,
                'stock' => 60,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Категория: Одежда (существующие товары)
            [
                'name' => 'Футболка Nike',
                'category' => 'clothing',
                'subcategory' => 'Мужская одежда',
                'description' => 'Хлопковая футболка для повседневной носки.',
                'price' => 29.99,
                'stock' => 100,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Платье Zara',
                'category' => 'clothing',
                'subcategory' => 'Женская одежда',
                'description' => 'Элегантное платье для вечернего выхода.',
                'price' => 59.99,
                'stock' => 50,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Нижнее белье Calvin Klein',
                'category' => 'clothing',
                'subcategory' => 'Нижнее белье',
                'description' => 'Комплект нижнего белья для женщин.',
                'price' => 39.99,
                'stock' => 70,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Новые товары для одежды
            [
                'name' => 'Детский комбинезон',
                'category' => 'clothing',
                'subcategory' => 'Детская одежда',
                'description' => 'Теплый комбинезон для детей.',
                'price' => 34.99,
                'stock' => 40,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Спортивный костюм Puma',
                'category' => 'clothing',
                'subcategory' => 'Спортивная одежда',
                'description' => 'Комплект для занятий спортом.',
                'price' => 79.99,
                'stock' => 30,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Коктейльное платье',
                'category' => 'clothing',
                'subcategory' => 'Платья',
                'description' => 'Короткое платье для вечеринок.',
                'price' => 49.99,
                'stock' => 35,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Мужской костюм Hugo Boss',
                'category' => 'clothing',
                'subcategory' => 'Костюмы и пиджаки',
                'description' => 'Классический костюм для деловых встреч.',
                'price' => 299.99,
                'stock' => 20,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Категория: Книги (существующие товары)
            [
                'name' => 'Роман "1984"',
                'category' => 'books',
                'subcategory' => 'Художественная литература',
                'description' => 'Классический роман-антиутопия Джорджа Оруэлла.',
                'price' => 14.99,
                'stock' => 50,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Комикс "Человек-паук"',
                'category' => 'books',
                'subcategory' => 'Комиксы',
                'description' => 'Комикс о приключениях Человека-паука.',
                'price' => 9.99,
                'stock' => 60,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Новые товары для книг
            [
                'name' => 'Книга "Квантовая физика"',
                'category' => 'books',
                'subcategory' => 'Научная литература',
                'description' => 'Введение в квантовую физику для начинающих.',
                'price' => 24.99,
                'stock' => 30,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Сказки Андерсена',
                'category' => 'books',
                'subcategory' => 'Детские книги',
                'description' => 'Сборник сказок для детей.',
                'price' => 19.99,
                'stock' => 40,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Учебник по математике',
                'category' => 'books',
                'subcategory' => 'Учебники',
                'description' => 'Учебник для 10 класса.',
                'price' => 29.99,
                'stock' => 50,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Аудиокнига "Мастер и Маргарита"',
                'category' => 'books',
                'subcategory' => 'Аудиокниги',
                'description' => 'Аудиоверсия знаменитого романа Булгакова.',
                'price' => 12.99,
                'stock' => 100,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Категория: Дом и сад (существующие товары)
            [
                'name' => 'Диван угловой',
                'category' => 'home',
                'subcategory' => 'Мебель',
                'description' => 'Угловой диван с мягкой обивкой.',
                'price' => 799.99,
                'stock' => 10,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Кухонный нож',
                'category' => 'home',
                'subcategory' => 'Кухонная утварь',
                'description' => 'Острый нож для нарезки продуктов.',
                'price' => 19.99,
                'stock' => 40,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Новые товары для дома и сада
            [
                'name' => 'Фоторамка декоративная',
                'category' => 'home',
                'subcategory' => 'Декор',
                'description' => 'Декоративная рамка для фотографий.',
                'price' => 14.99,
                'stock' => 50,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Секатор садовый',
                'category' => 'home',
                'subcategory' => 'Садовые инструменты',
                'description' => 'Инструмент для обрезки растений.',
                'price' => 24.99,
                'stock' => 30,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Настольная лампа',
                'category' => 'home',
                'subcategory' => 'Освещение',
                'description' => 'Лампа с регулировкой яркости.',
                'price' => 39.99,
                'stock' => 25,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Плед шерстяной',
                'category' => 'home',
                'subcategory' => 'Текстиль для дома',
                'description' => 'Теплый плед для уютных вечеров.',
                'price' => 29.99,
                'stock' => 40,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Садовый столик',
                'category' => 'home',
                'subcategory' => 'Садовая мебель',
                'description' => 'Компактный столик для сада.',
                'price' => 89.99,
                'stock' => 15,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Категория: Спорт и развлечения (существующие товары)
            [
                'name' => 'Беговая дорожка',
                'category' => 'sports',
                'subcategory' => 'Тренажеры',
                'description' => 'Электрическая беговая дорожка с регулировкой скорости.',
                'price' => 599.99,
                'stock' => 10,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Палатка для кемпинга',
                'category' => 'sports',
                'subcategory' => 'Кемпинг и походы',
                'description' => 'Палатка на 4 человека для походов.',
                'price' => 129.99,
                'stock' => 20,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Новые товары для спорта и развлечений
            [
                'name' => 'Спортивные леггинсы',
                'category' => 'sports',
                'subcategory' => 'Спортивная одежда',
                'description' => 'Удобные леггинсы для тренировок.',
                'price' => 34.99,
                'stock' => 50,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Спортивный рюкзак',
                'category' => 'sports',
                'subcategory' => 'Аксессуары',
                'description' => 'Рюкзак для спортивного инвентаря.',
                'price' => 44.99,
                'stock' => 30,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Горный велосипед',
                'category' => 'sports',
                'subcategory' => 'Велосипеды',
                'description' => 'Велосипед для пересеченной местности.',
                'price' => 399.99,
                'stock' => 10,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Удочка для рыбалки',
                'category' => 'sports',
                'subcategory' => 'Рыбалка',
                'description' => 'Удочка для ловли рыбы.',
                'price' => 59.99,
                'stock' => 20,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Гантели 5 кг',
                'category' => 'sports',
                'subcategory' => 'Фитнес-оборудование',
                'description' => 'Пара гантелей для тренировок.',
                'price' => 49.99,
                'stock' => 25,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Категория: Красота и здоровье (существующие товары)
            [
                'name' => 'Тушь для ресниц Maybelline',
                'category' => 'beauty',
                'subcategory' => 'Косметика',
                'description' => 'Тушь для объема и удлинения ресниц.',
                'price' => 12.99,
                'stock' => 80,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Крем для лица Nivea',
                'category' => 'beauty',
                'subcategory' => 'Средства по уходу за кожей',
                'description' => 'Увлажняющий крем для лица.',
                'price' => 15.99,
                'stock' => 60,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Новые товары для красоты и здоровья
            [
                'name' => 'Парфюм Chanel No.5',
                'category' => 'beauty',
                'subcategory' => 'Парфюмерия',
                'description' => 'Классический женский аромат.',
                'price' => 99.99,
                'stock' => 30,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Кисть для макияжа',
                'category' => 'beauty',
                'subcategory' => 'Инструменты для макияжа',
                'description' => 'Кисть для нанесения тонального крема.',
                'price' => 9.99,
                'stock' => 50,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Шампунь L\'Oreal',
                'category' => 'beauty',
                'subcategory' => 'Средства для волос',
                'description' => 'Питательный шампунь для всех типов волос.',
                'price' => 12.99,
                'stock' => 40,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Пояс для похудения',
                'category' => 'beauty',
                'subcategory' => 'Средства для похудения',
                'description' => 'Пояс для сжигания жира.',
                'price' => 29.99,
                'stock' => 20,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Категория: Украшения и аксессуары (существующие товары)
            [
                'name' => 'Серебряное ожерелье',
                'category' => 'jewelry',
                'subcategory' => 'Ожерелья',
                'description' => 'Ожерелье из серебра с подвеской.',
                'price' => 49.99,
                'stock' => 30,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Часы Casio',
                'category' => 'jewelry',
                'subcategory' => 'Часы',
                'description' => 'Классические наручные часы.',
                'price' => 79.99,
                'stock' => 25,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Новые товары для украшений
            [
                'name' => 'Серьги с жемчугом',
                'category' => 'jewelry',
                'subcategory' => 'Серьги',
                'description' => 'Элегантные серьги с натуральным жемчугом.',
                'price' => 39.99,
                'stock' => 35,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Кольцо с бриллиантом',
                'category' => 'jewelry',
                'subcategory' => 'Кольца',
                'description' => 'Золотое кольцо с бриллиантом.',
                'price' => 999.99,
                'stock' => 5,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Браслет из бисера',
                'category' => 'jewelry',
                'subcategory' => 'Браслеты',
                'description' => 'Ручной работы браслет из бисера.',
                'price' => 19.99,
                'stock' => 40,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Заколка для волос',
                'category' => 'jewelry',
                'subcategory' => 'Аксессуары для волос',
                'description' => 'Заколка с цветочным дизайном.',
                'price' => 9.99,
                'stock' => 50,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Категория: Обувь (существующие товары)
            [
                'name' => 'Кроссовки Adidas',
                'category' => 'shoes',
                'subcategory' => 'Спортивная обувь',
                'description' => 'Удобные кроссовки для бега.',
                'price' => 89.99,
                'stock' => 40,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Женские туфли',
                'category' => 'shoes',
                'subcategory' => 'Туфли',
                'description' => 'Элегантные туфли на каблуке.',
                'price' => 69.99,
                'stock' => 30,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Новые товары для обуви
            [
                'name' => 'Мужские ботинки Timberland',
                'category' => 'shoes',
                'subcategory' => 'Мужская обувь',
                'description' => 'Прочные ботинки для зимы.',
                'price' => 129.99,
                'stock' => 20,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Женские кеды Converse',
                'category' => 'shoes',
                'subcategory' => 'Женская обувь',
                'description' => 'Классические кеды для повседневной носки.',
                'price' => 59.99,
                'stock' => 30,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Детские сандалии',
                'category' => 'shoes',
                'subcategory' => 'Детская обувь',
                'description' => 'Легкие сандалии для детей.',
                'price' => 24.99,
                'stock' => 40,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Сапоги зимние',
                'category' => 'shoes',
                'subcategory' => 'Сапоги',
                'description' => 'Теплые сапоги для холодной погоды.',
                'price' => 99.99,
                'stock' => 25,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Категория: Сумки и аксессуары (существующие товары)
            [
                'name' => 'Рюкзак Xiaomi',
                'category' => 'bags',
                'subcategory' => 'Рюкзаки',
                'description' => 'Стильный рюкзак для повседневного использования.',
                'price' => 39.99,
                'stock' => 50,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Кошелек из кожи',
                'category' => 'bags',
                'subcategory' => 'Кошельки',
                'description' => 'Кожаный кошелек с отделением для карт.',
                'price' => 29.99,
                'stock' => 60,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Новые товары для сумок
            [
                'name' => 'Сумка через плечо Gucci',
                'category' => 'bags',
                'subcategory' => 'Сумки через плечо',
                'description' => 'Модная сумка для повседневного использования.',
                'price' => 199.99,
                'stock' => 15,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Чемодан Samsonite',
                'category' => 'bags',
                'subcategory' => 'Путешествия и багаж',
                'description' => 'Прочный чемодан для путешествий.',
                'price' => 149.99,
                'stock' => 20,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Сумка для ноутбука',
                'category' => 'bags',
                'subcategory' => 'Сумки для ноутбуков',
                'description' => 'Сумка для ноутбука 15 дюймов.',
                'price' => 49.99,
                'stock' => 30,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Категория: Игрушки и хобби (существующие товары)
            [
                'name' => 'Конструктор LEGO',
                'category' => 'toys',
                'subcategory' => 'Конструкторы',
                'description' => 'Набор LEGO для детей от 6 лет.',
                'price' => 49.99,
                'stock' => 40,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Настольная игра "Монополия"',
                'category' => 'toys',
                'subcategory' => 'Настольные игры',
                'description' => 'Классическая игра для всей семьи.',
                'price' => 29.99,
                'stock' => 30,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Новые товары для игрушек
            [
                'name' => 'Кукла Barbie',
                'category' => 'toys',
                'subcategory' => 'Куклы',
                'description' => 'Кукла с набором одежды.',
                'price' => 24.99,
                'stock' => 50,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Мягкая игрушка Мишка',
                'category' => 'toys',
                'subcategory' => 'Игрушки для малышей',
                'description' => 'Плюшевый мишка для детей.',
                'price' => 19.99,
                'stock' => 60,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Радиоуправляемая машина',
                'category' => 'toys',
                'subcategory' => 'Радиоуправляемые игрушки',
                'description' => 'Машина с пультом управления.',
                'price' => 39.99,
                'stock' => 25,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Пазл 1000 деталей',
                'category' => 'toys',
                'subcategory' => 'Пазлы',
                'description' => 'Пазл с изображением природы.',
                'price' => 14.99,
                'stock' => 40,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Категория: Бытовая техника (существующие товары)
            [
                'name' => 'Блендер Philips',
                'category' => 'appliances',
                'subcategory' => 'Кухонные приборы',
                'description' => 'Мощный блендер для смузи и коктейлей.',
                'price' => 59.99,
                'stock' => 20,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Пылесос Dyson',
                'category' => 'appliances',
                'subcategory' => 'Чистящие устройства',
                'description' => 'Беспроводной пылесос с высокой мощностью.',
                'price' => 299.99,
                'stock' => 15,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Новые товары для бытовой техники
            [
                'name' => 'Утюг Tefal',
                'category' => 'appliances',
                'subcategory' => 'Техника для дома',
                'description' => 'Утюг с паровой функцией.',
                'price' => 49.99,
                'stock' => 25,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Кондиционер LG',
                'category' => 'appliances',
                'subcategory' => 'Климатизация',
                'description' => 'Настенный кондиционер для дома.',
                'price' => 599.99,
                'stock' => 10,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Электрический чайник',
                'category' => 'appliances',
                'subcategory' => 'Мелкая бытовая техника',
                'description' => 'Чайник с быстрым нагревом.',
                'price' => 29.99,
                'stock' => 40,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Категория: Автотовары (существующие товары)
            [
                'name' => 'Автомобильный видеорегистратор',
                'category' => 'auto',
                'subcategory' => 'Автомобильная электроника',
                'description' => 'Видеорегистратор с записью в Full HD.',
                'price' => 79.99,
                'stock' => 25,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Набор инструментов для авто',
                'category' => 'auto',
                'subcategory' => 'Инструменты для авто',
                'description' => 'Набор инструментов для ремонта автомобиля.',
                'price' => 49.99,
                'stock' => 30,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Новые товары для автотоваров
            [
                'name' => 'Автомобильный коврик',
                'category' => 'auto',
                'subcategory' => 'Аксессуары для автомобилей',
                'description' => 'Коврик для салона автомобиля.',
                'price' => 19.99,
                'stock' => 50,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Зимняя шина Michelin',
                'category' => 'auto',
                'subcategory' => 'Шины и диски',
                'description' => 'Зимняя шина для легкового автомобиля.',
                'price' => 99.99,
                'stock' => 20,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Масляный фильтр',
                'category' => 'auto',
                'subcategory' => 'Запчасти',
                'description' => 'Фильтр для двигателя автомобиля.',
                'price' => 14.99,
                'stock' => 60,
                'image' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];
        $i = 0;
        foreach ($products as $product) {
            $category = Category::where('key', $product['category'])->first();
            $subcategory = Subcategory::where('name', $product['subcategory'])
                ->where('category_id', $category->id)
                ->first();
            Product::create([
                'name' => $product['name'],
                'category_id' => $category->id,
                'subcategory_id' => $subcategory ? $subcategory->id : null,
                'description' => $product['description'],
                'price' => $product['price'],
                'stock' => $product['stock'],
                'image' => $product['image'],
                'seller_id' => $sellerIds[$i % count($sellerIds)],
                'is_approved' => true, // Все товары подтверждены
                'created_at' => $product['created_at'],
                'updated_at' => $product['updated_at'],
            ]);
            $i++;
        }
    }
}
